# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Traveling through the Web"
description: > # this means to ignore newlines until "email:"
   A beautiful journey through all aspects of web design and development.

email: a-mail@mail.mail
#blog logo
logo: "assets/images/logo.jpg"
# blog cover
cover: "assets/images/2Planes.jpg"

name: 'Gary Caseman'
author: 'Gary Caseman'
author_image: "assets/images/avatar.png"

paginate:	5

url: "https://wingsfan70.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@wingsfan70'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wingsfan70
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/wingsfan70
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
